image_root: './dataset/coco2014/caption_images/'
disturbance_image_root: './dataset/coco2014/disturbance_images/'
ann_root: './dataset/coco2014/'

remain: 'remain_data_match.json'


sensitive_train: 'resume.json'

sensitive_val: 'resume_val.json'

sensitive_val_gt: 'resume_val_gt.json'

val: 'coco_karpathy_val.json'
test: 'coco_karpathy_test.json'
remain_val: 'coco_karpathy_remain_val.json'
remain_val_gt: 'coco_karpathy_remain_val_gt.json'
val_gt: 'coco_karpathy_val_gt.json'
test_gt: 'coco_karpathy_test_gt.json'


pretrained: './output/Caption_coco_sensitive_resume/checkpoint_best.pth'


param_indices: './compute_params/coco/resume/parameter_indices_l3.json'


target_layers: '9,10,11'

gamma1: 0.1
gamma2: 10.0
gamma3: 0.2

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
# batch_size: 16
batch_size: 16
init_lr: 1e-5



image_size: 384

# generation configs
max_length: 35
min_length: 5
num_beams: 3
prompt: 'a picture of '

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 5

